@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Account *-right-> "1" UniqueExpenditureList

UniqueExpenditureList o-right-> Expenditure

Expenditure *--> "1" Tag
Expenditure *--> "1" Info
Expenditure *--> "1  "Amount
Expenditure *--> "1" Date

@enduml
