@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TopLevelParser" as TopLevelParser LOGIC_COLOR
participant ":ExpLevelParser" as ExpLevelParser LOGIC_COLOR
participant ":ExpDeleteCommandParser" as ExpDeleteCommandParser LOGIC_COLOR
participant "d:ExpDeleteCommand" as ExpDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("exp delete 1")
activate LogicManager

LogicManager -> TopLevelParser : parseCommand("exp delete 1")
activate TopLevelParser

create ExpLevelParser
TopLevelParser -> ExpLevelParser
activate ExpLevelParser
TopLevelParser -> ExpLevelParser : parseCommand("delete 1")

create ExpDeleteCommandParser
ExpLevelParser -> ExpDeleteCommandParser
activate ExpDeleteCommandParser
ExpLevelParser -> ExpDeleteCommandParser : parse("1")

create ExpDeleteCommand
ExpDeleteCommandParser -> ExpDeleteCommand
activate ExpDeleteCommand

ExpDeleteCommand --> ExpDeleteCommandParser : d
deactivate ExpDeleteCommand

ExpDeleteCommandParser --> ExpLevelParser : d
deactivate ExpDeleteCommandParser
ExpDeleteCommandParser -[hidden]-> ExpLevelParser
destroy ExpDeleteCommandParser

ExpLevelParser --> TopLevelParser : d
deactivate ExpLevelParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ExpLevelParser -[hidden]-> TopLevelParser
destroy ExpLevelParser

TopLevelParser --> LogicManager : d
deactivate TopLevelParser

LogicManager -> ExpDeleteCommand : execute()
activate ExpDeleteCommand

ExpDeleteCommand -> Model : deleteExpenditure(1)
activate Model

Model --> ExpDeleteCommand
deactivate Model

create CommandResult
ExpDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> ExpDeleteCommand
deactivate CommandResult

ExpDeleteCommand --> LogicManager : result
deactivate ExpDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
