@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package Parser {
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
}

Interface Logic <<Interface>>
Class LogicManager
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -down-> Parser

Parser .right.> XYZCommand : creates

XYZCommand -|> Command
LogicManager ..> Command : executes >

LogicManager --> Model
Command ..> Model
note bottom of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc


Logic .down.> CommandResult
LogicManager .down.> CommandResult
Command .> CommandResult
@enduml
