@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class Account
Class ModelManager

Package Expenditure {
Class "{abstract}\nBaseExp" as BaseExp
Class Expenditure
Class Repeat
Class Amount
Class Date
Class Info
Class Tag
Class UniqueExpenditureList
Class Period <<enumeration>>
}


Class HiddenOutside #FFFFFF

Account *--> "1" UniqueExpenditureList
Account *--> "*" Repeat

Repeat -up-|> BaseExp
Expenditure -up-|> BaseExp
UniqueExpenditureList o--> "*" Expenditure
BaseExp *--> "1" Amount
BaseExp *--> "1" Tag
BaseExp *--> "1" Info
Expenditure *--> "1" Date
Repeat *--> "1" Date : startDate >
Repeat *--> "1" Date : endDate >
Repeat *--> "1" Period

ModelManager --> "1" BaseExp : filtered list
@enduml
