@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAccountList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ReadOnlyAccountList <<Interface>>
Class ReportableAccount <<Interface>>
Class ReadOnlyAccount <<Interface>>
Class AccountList
Class Account
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Expenditure {
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AccountList .left.|> ReadOnlyAccountList
Account .up.|> ReadOnlyAccount
Account .up.|> ReportableAccount

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AccountList
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ReadOnlyAccountList .down.|> ReadOnlyAccount
Account -left-> Expenditure
AccountList *--> "*" Account

ModelManager --> Expenditure
@enduml
