@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

show field

package UI <<Rectangle>>{
Class "{abstract}\nUiPart" as UiPart
Class ReportWindow  {
  <color:white> {field} {static} currentGraph:Graph
                   }
Class ResultDisplay
Class ReportCommandBox
Class MenuBar
Class MainWindow
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

MainWindow -up-> Logic

ReportWindow -up-> Logic
MainWindow *--> ReportWindow


ReportWindow *-down-> ReportCommandBox
ReportWindow *-down-> MenuBar
ReportWindow *--> ResultDisplay

MainWindow -down-|> UiPart
ReportWindow -down-|> UiPart
ReportCommandBox -down-|> UiPart
ResultDisplay -down-|> UiPart

@enduml

