@startuml
!include style.puml
title Report View Sequence
box Logic LOGIC_COLOR_T1
participant ":ReportLevelParser" as ReportLevelParser LOGIC_COLOR
participant ":ViewReportCommandParser" as ViewReportCommandParser LOGIC_COLOR
participant "vc:ViewReportCommand" as ViewReportCommand LOGIC_COLOR
participant ":GenerateStats" as GenerateStats LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":Report" as Report MODEL_COLOR
end box

box Pie UI_COLOR_T1
participant ":Pie" as Pie UI_COLOR
end box
activate ReportLevelParser
create ViewReportCommandParser
ReportLevelParser -> ViewReportCommandParser
activate ViewReportCommandParser
ReportLevelParser -> ViewReportCommandParser : parse("-sd 2020-03-01\n -ed 2020-03-31 -g pie -o tag")
create Report
ViewReportCommandParser -> Report
activate Report
Report ---> ViewReportCommandParser
deactivate Report
create ViewReportCommand
ViewReportCommandParser -> ViewReportCommand
activate ViewReportCommand
ViewReportCommand --> ViewReportCommandParser : vc
ViewReportCommandParser --> ReportLevelParser : vc
deactivate ViewReportCommandParser
[<-[hidden]- ViewReportCommandParser
destroy ViewReportCommandParser
[<--ReportLevelParser :vc
deactivate ReportLevelParser
[<-[hidden]-ReportLevelParser
destroy ReportLevelParser


[-> ViewReportCommand : execute()
create GenerateStats
ViewReportCommand -> GenerateStats
activate GenerateStats
ViewReportCommand -> GenerateStats : generateStatsByTags()
activate Model
GenerateStats -> Model : getReportableAccount()
Model --> GenerateStats : reportableAcct
deactivate Model
GenerateStats --> ViewReportCommand : stats
deactivate GenerateStats
GenerateStats -[hidden]-> ViewReportCommand
destroy GenerateStats
activate Report
ViewReportCommand -> Report : getOrganise()
Report --> ViewReportCommand : organise
ViewReportCommand -> Report : getFormat()
Report --> ViewReportCommand : format
deactivate Report
Report -[hidden]-> ViewReportCommand
destroy Report
create Pie
ViewReportCommand -> Pie : new Pie (stats, organise)
activate Pie
Pie --> ViewReportCommand
deactivate Pie
create CommandResult
ViewReportCommand -> CommandResult
activate CommandResult
CommandResult --> ViewReportCommand : result
deactivate CommandResult
[<- ViewReportCommand : result
deactivate ViewReportCommand
[<-[hidden]- ViewReportCommand
destroy ViewReportCommand

@enduml
