@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ReportWindow
Class ResultDisplay
Class ExpenditureListPanel
Class ExpenditureCard
Class StatusBarFooter
Class CommandBox
Class CalendarView
Class BudgetView
Class ActiveNameAndDateView
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .up.|> Ui
UiManager -left-> MainWindow
MainWindow *--right-> CalendarView
MainWindow -down-> ReportWindow
MainWindow *---> CommandBox
MainWindow *---> ResultDisplay
MainWindow *---> ExpenditureListPanel
MainWindow *--> ActiveNameAndDateView
MainWindow *--> BudgetView
MainWindow *--> StatusBarFooter

ExpenditureListPanel -down-> ExpenditureCard

MainWindow --|> UiPart
CalendarView -|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
ExpenditureListPanel --|> UiPart
ExpenditureCard --|> UiPart
StatusBarFooter --|> UiPart
ReportWindow --|> UiPart
BudgetView -down-|> UiPart
ActiveNameAndDateView -|> UiPart

ExpenditureCard ..> Model
UiManager -right-> Logic
MainWindow --> Logic
ReportWindow -up-> Logic

CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
MainWindow -[hidden]-|> UiPart
@enduml



