@startuml
start
:User types in command;
if () then ([command is correct])
    :Executes command;
     if() then ([view command])
     :Report window shows updated report;
     else ([print/export/exit command])
            if () then ([print/export command])
             if () then ([has graph])
                :Prints/exports the report shown in report window;
             else ([else])
                :Throw error message;
              endif
            else ([exit command])
                 :Exits Report Window;
                endif
      endif
else ([else])
    :Throw error message;
endif
stop
@enduml


