@startuml
(*)If "Report Window" then
-->[Yes] " User enters command"
--> If "input is correct" then
--> [Yes] "Updates report"
-->(*)
else
-->"Doesnt update report"
Endif
-->(*)
else
--> "User enters command "
If "input is correct" then
--> [Yes] "pop out report window with report shown"
-->(*)
else
--> "throw error"
Endif
-->(*)
@enduml