@startuml
start
:User types in report command;
if () then ([command is correct])
    :Executes command;
     if() then ([view command])
     :Pops up report window and shows report;
     else ([print/export command])
     :Prints/export the report;
     endif
else ([else])
    :Throw error message;
endif
stop
@enduml
