= Jiang Jiahui - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: $AVE IT

---

== Overview

$AVE IT is a desktop budget management application. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

== Summary of contributions

* *Major enhancement*: added *the disjoint accounts feature*
** What it does: The disjoint accounts feature allows the user to better organise their expenditures in multiple accounts.
** Justification: As the user may have taken on multiple roles/project that require them to manage expenses, they can create one account for each of their roles/projects, in addition to one for their personal expenses. This way, they can track all of their expenditures in this one application, while keep them organised in disjoint accounts.
** Highlights:
*** This feature required major changed to the backend Storage package as the structure of the Model classes has changed significantly.
*** It was challenging to ensure that this feature works seamlessly with the UI. For example, when a different account is checked-out, multiple UI components are updated.

* *Minor enhancement*: improved the `find` command
** What it does: Allows the user to search for multiple keywords, a tag, or both together.

* *Minor enhancement*: improved the `ExpenditureListPanel` UI component
** What it does: Used polymorphism to allow expenditures and repeats to be displayed in the same list.

* *Code contributed*: [https://nus-cs2103-ay1920s2.github.io/tp-dashboard/#search=&sort=groupTitle&sortWithin=title&since=2020-02-14&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=JJiahui&tabRepo=AY1920S2-CS2103T-T10-3%2Fmain%5Bmaster%5D[RepoSense]]

* *Other contributions*:

** Project management:
*** Managed releases `v1.1` - `v1.4` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated error messages of commands to be more informative and helpful to the user.
** Documentation:
*** Added documentation for `Account` and `Expenditure` to the User Guide and Developer Guide
** Community:
*** PRs reviewed: https://github.com/AY1920S2-CS2103T-T10-3/main/pull/6[#6], https://github.com/AY1920S2-CS2103T-T10-3/main/pull/8[#8], https://github.com/AY1920S2-CS2103T-T10-3/main/pull/15[#15]
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com/JJiahui/ped/issues/1[#1], https://github.com/JJiahui/ped/issues/2[#2], https://github.com/JJiahui/ped/issues/3[#3])

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=account]
include::../UserGuide.adoc[tag=expenditure]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=account]
include::../DeveloperGuide.adoc[tag=expenditure]
